"""Clean up polluted category tag registries.

When categories were generated by an over-permissive LLM tagger
(common during `--bootstrap`), the same generic tags end up in every
category: `anime`, `pastel`, `blue`, `detailed`, `minimalist`, `neon`,
`retro`, `digital-art`, `illustration`, `simple`, `monochrome`,
`cyberpunk`, etc. These stop being discriminative and the
multi-signal classifier ends up routing everything to the category
that happens to match by chance (often `Anime` because it's the
biggest bag of tags).

This module:
  1. Counts document frequency of every tag across categories.
  2. Flags as "polluted" any tag present in >= `polluted_threshold` of
     categories (default 50%).
  3. Optionally removes the polluted tags from every `.category.json`.
     Keeps each category's `tags` list at a sane max length.
  4. Reports what it removed and why.

Safe to run: it only ever removes tags, never adds new ones, and
writes a `.bak` next to every modified `category.json`.
"""
from __future__ import annotations

import json
import os
import shutil
from collections import Counter
from typing import Dict, List, Optional, Set, Tuple

from . import categories as c
from .tags import _tags_flat


# Default: a tag is considered polluted if it appears in >= this
# fraction of categories. Lower = stricter cleaning.
DEFAULT_POLLUTED_THRESHOLD = 0.50

# Even if a tag survives the pollution filter, it is dropped from a
# category if the category already has more than this many tags.
# Real-world wallpaper folders typically benefit from 10-30 tags; more
# than that is almost always bloat.
DEFAULT_MAX_TAGS_PER_CATEGORY = 25

# Tags that are always preserved if they appear (these are genuinely
# useful category signatures).
ALWAYS_KEEP = {
    "anime", "photograph", "photo", "illustration", "digital-art",
    "pixel-art", "painting", "sketch", "3d-render", "minimalist",
    "monochrome", "portrait", "landscape",
}


def _read_category_config(path: str) -> dict:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _write_category_config(path: str, cfg: dict, backup: bool = True) -> None:
    if backup and os.path.exists(path):
        backup_path = path + ".bak"
        if not os.path.exists(backup_path):
            shutil.copy2(path, backup_path)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)
    os.replace(tmp, path)


def analyse_pollution(
    categories_dir: Optional[str] = None,
) -> Tuple[Dict[str, Set[str]], Dict[str, int]]:
    """Return the set of polluted tags and a per-tag document-frequency map.

    A tag is "polluted" if it appears in >= 50% of the categories that
    have any tags at all. The classification is purely based on the
    frequency distribution; no value judgements are made.
    """
    target_dir = categories_dir or c.CATEGORIES_DIR
    if not target_dir or not os.path.isdir(target_dir):
        return {}, {}

    # Re-discover categories so we get the live CATEGORIES list.
    c.discover_categories(target_dir)
    valid = list(c.CATEGORIES)
    n = len(valid)
    if n == 0:
        return {}, {}

    df: Counter = Counter()
    cat_tags_map: Dict[str, List[str]] = {}
    for cat in valid:
        cfg = c.get_category_config(cat) or {}
        tags = cfg.get("tags") or []
        # Lowercase, drop blanks, drop dupes within the same category.
        seen: Set[str] = set()
        clean: List[str] = []
        for t in tags:
            tl = str(t).strip().lower()
            if not tl or tl in seen:
                continue
            seen.add(tl)
            clean.append(tl)
        cat_tags_map[cat] = clean
        for t in clean:
            df[t] += 1

    polluted = {t for t, d in df.items() if d >= DEFAULT_POLLUTED_THRESHOLD * n}
    return polluted, dict(df)


def clean_category_tags(
    categories_dir: Optional[str] = None,
    polluted_threshold: float = DEFAULT_POLLUTED_THRESHOLD,
    max_tags_per_category: int = DEFAULT_MAX_TAGS_PER_CATEGORY,
    backup: bool = True,
    dry_run: bool = False,
) -> Dict[str, Dict]:
    """Strip polluted tags from every category in `categories_dir`.

    Returns a summary {category: {"removed": [...], "kept": int, "before": int}}.
    When `dry_run` is True nothing is written; the summary reflects what
    *would* happen.
    """
    target_dir = categories_dir or c.CATEGORIES_DIR
    if not target_dir or not os.path.isdir(target_dir):
        return {}

    c.discover_categories(target_dir)
    valid = list(c.CATEGORIES)
    if not valid:
        return {}

    # Document frequency over the current live config (not the
    # polluted one we're about to fix - we recompute per category).
    summary: Dict[str, Dict] = {}
    for cat in valid:
        cfg_path = os.path.join(target_dir, cat, ".category.json")
        cfg = _read_category_config(cfg_path)
        if not cfg:
            continue
        original_tags = [str(t).strip().lower() for t in (cfg.get("tags") or []) if str(t).strip()]
        original_set = list(dict.fromkeys(original_tags))  # dedupe, preserve order

        # Recompute df for the new state to handle iterative cleaning.
        per_n = len(valid)
        df: Counter = Counter()
        for other in valid:
            if other == cat:
                continue
            other_cfg = _read_category_config(os.path.join(target_dir, other, ".category.json"))
            for t in (other_cfg.get("tags") or []):
                df[str(t).strip().lower()] += 1
        # Include the current category too (since we're going to keep it).
        for t in original_set:
            df[t] += 1

        polluted: Set[str] = {t for t, d in df.items() if d >= polluted_threshold * per_n}
        # Drop polluted tags (but always keep the protected set).
        kept = [t for t in original_set
                if t in ALWAYS_KEEP or t not in polluted]
        # Cap length.
        if len(kept) > max_tags_per_category:
            kept = kept[:max_tags_per_category]

        removed = [t for t in original_set if t not in kept]
        summary[cat] = {
            "before": len(original_set),
            "kept": len(kept),
            "removed": removed,
            "path": cfg_path,
        }

        if not dry_run and removed:
            cfg["tags"] = kept
            _write_category_config(cfg_path, cfg, backup=backup)

    return summary


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _print_pollution_report(polluted: Set[str], df: Dict[str, int], n: int) -> None:
    if not polluted:
        print(f"No polluted tags detected across {n} categories.")
        return
    print(f"Detected {len(polluted)} polluted tag(s) (present in >=50% of categories):")
    print()
    print(f"  {'tag':<22s} {'df':>4s} / {n}  examples")
    print(f"  {'-'*22}  {'-'*7}  {'-'*30}")
    for t in sorted(polluted, key=lambda x: -df[x]):
        df_t = df[t]
        # Find 3 categories that use this tag for examples.
        examples = []
        for cat in c.CATEGORIES:
            cfg = c.get_category_config(cat)
            if cfg and t in [str(x).lower() for x in (cfg.get("tags") or [])]:
                examples.append(cat)
                if len(examples) >= 3:
                    break
        example_str = ", ".join(examples[:3])
        if len(examples) > 3:
            example_str += f", ... (+{len(examples) - 3})"
        print(f"  {t:<22s} {df_t:>4d}  {example_str}")


def main(argv: Optional[List[str]] = None) -> int:
    """Entry point: `python -m wallpaper_analyzer.clean_tags [args]`.

    Use `--analyse` (default) to just report polluted tags.
    Use `--clean` to strip them (with a backup)."""
    import argparse
    p = argparse.ArgumentParser(
        prog="python -m wallpaper_analyzer.clean_tags",
        description="Detect and clean polluted tags in the category registry.",
    )
    p.add_argument("--analyse", action="store_true", default=True,
                   help="Analyse and report polluted tags (default).")
    p.add_argument("--clean", action="store_true",
                   help="Strip polluted tags from every category (writes .bak files).")
    p.add_argument("--dry-run", action="store_true",
                   help="With --clean, just print what would be removed.")
    p.add_argument("--threshold", type=float, default=DEFAULT_POLLUTED_THRESHOLD,
                   help="Pollution threshold (fraction of categories).")
    p.add_argument("--max-tags", type=int, default=DEFAULT_MAX_TAGS_PER_CATEGORY,
                   help="Cap each category at this many tags after cleaning.")
    p.add_argument("--categories-dir", default=None,
                   help="Path to the categories directory (default: settings.dest_dir).")
    args = p.parse_args(argv)

    target_dir = args.categories_dir or c.CATEGORIES_DIR
    if not target_dir:
        print("ERROR: no categories directory (set in .wallpaper_analyzer.json or pass --categories-dir)")
        return 1

    if not args.clean:
        polluted, df = analyse_pollution(target_dir)
        if not c.CATEGORIES:
            c.discover_categories(target_dir)
        n = len(c.CATEGORIES)
        _print_pollution_report(polluted, df, n)
        return 0

    # Clean path
    summary = clean_category_tags(
        categories_dir=target_dir,
        polluted_threshold=args.threshold,
        max_tags_per_category=args.max_tags,
        backup=True,
        dry_run=args.dry_run,
    )
    if args.dry_run:
        print(f"[dry-run] Would remove polluted tags from {len(summary)} categories:")
    else:
        print(f"Cleaned {len(summary)} categories:")
    total_removed = 0
    for cat, info in summary.items():
        if info["removed"]:
            print(f"  {cat:12s}: {info['before']:3d} -> {info['kept']:3d}  "
                  f"({len(info['removed'])} removed: {', '.join(info['removed'][:6])}"
                  f"{' ...' if len(info['removed']) > 6 else ''})")
            total_removed += len(info["removed"])
    print(f"\nTotal tags removed: {total_removed}")
    if args.dry_run:
        print("Nothing was written. Re-run without --dry-run to apply.")
    else:
        print("Backups were saved next to each .category.json as .bak")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv[1:]))
